### ISSUE TITLE
Customizer Header Settings

### ISSUE THREAD

**Issue by badcat** [ThemeAwesome/wp-forge#53]
Hi - In Customizer > Header Settings > Site Identity under Tagline section.

Seems like "Display Site Title and Tagline" is duplicative to the above options; "Hide site title" and "Hide site tagline"? I'd think we'd only need the first two and not the third, no?

![customizer](https://user-images.githubusercontent.com/26096/29597308-d2782788-878f-11e7-85e8-4456b9780576.png)

There's also some capitalization issue :)  

thanks.

**Comment by tsquez** [comment]
One is for the custom logo the other is for the custom header... when you
have both they both appear... trying to figure out how to remove one...
sand the capitalization is a matter of preference yah grammer nazi... lol

via my phone

**Comment by tsquez** [comment]
Forgot to mention, the new theme only uses the custom logo,  not both...a
lot of surprises coming amigo... toy gonna love it ;)

via my phone

**Comment by badcat** [comment]
Hmm - seems to exhibit strange hiding behavior without using Custom Logo or Custom Header (img). Maybe it just needs to be labeled more clearly?  Not sure exactly what that would be though.  Er.. thoughts?

LOL - yeah I was mentioning the capitalization only because the items were handle differently and they were directly under the other choices.  (rib rib... and you spelled grammar all funny too :)

**Comment by badcat** [comment]
Also... you mention, _"Forgot to mention, the new theme only uses the custom logo,  not both."_
But the Customizer > Header Settings > Header Image is still there and allows both -- is the Custom Header Image really going away?

**Comment by tsquez** [comment]
Yes, it's basically the same thing, just one is called custom header and
other custom logo. The custom logo is easier to implement.  Read up on it.

The only reason both are there is because, when I took away the custom
header and added the custom logo a few users complained because it
destroyed the headers they had built.

So I added the custom header back into the mix and that is why you see so I
added the custom header back into the mix and that is why you see duplicate
site title and site description.

I have been trying to figure out a way how to use just one instance of the
site title and site description but I got busy working on the new theme and
completely forgot about that until you brought it up... LOL.

Have you heard of generatepress? If you haven't look into that theme and
then think about generatepress using Foundation.

+ look into a plug-in called Kirki. That's what we'll be going into the new
theme.

via my phone

**Comment by badcat** [comment]
Yes - I'm pretty familiar with GP. I've built about a dozen sites with it this year :)  You'll see me lurking around Tom's GitHub and Forums. 

Also yes to Kirki of course; Was playing with this.. https://www.youtube.com/watch?v=Bqv175VbOM0 I assume many of the page builders out there will continue the move to Kirki or similar.  Looking forward to seeing what you're working on 👍

**Comment by tsquez** [comment]
Cool cool, like I said, just think of GeneratePress running on Foundation for Sites with Kirki built in….so far I think it’s pretty damn cool 😃

**Comment by badcat** [comment]
I'm game - show it  :)  Got a name picked yet?

**Comment by tsquez** [comment]
Hahahahah yeah I can shot it to yah and yes I have a name for it. If you want a look hit me up on my personal email and I'll send you the link to the demo 😉 ...gonna close this 👍
