### ISSUE TITLE
Flex widget menu look bad

### ISSUE THREAD

**Issue by dlyr** [ThemeAwesome/WP-Forge#55]
WordPress 4.9.7 running WP-Forge theme 6.4.3.3 site
[http://departement-informatique.univ-tlse3.fr/master-igai/](http://departement-informatique.univ-tlse3.fr/master-igai/)

Hi there, seems like flex option to table menu is causing some awefull layout on side menu (but if I remove it using firefox css inspector, it breaks to nav menu layout).
Here are two screen shots, the first with flex on (see how Accueil and Présentation are on the same line)

![flex-on](https://user-images.githubusercontent.com/11328509/42867162-02ab42f4-8a6f-11e8-9f1c-0e85724bdffd.png)

Here off, looks better

![flex-off](https://user-images.githubusercontent.com/11328509/42867161-027fa874-8a6f-11e8-8615-e040bff7a85b.png)

Maybe a solution is to have different layout if menu is used in nav or side widget.

Btw, with older version I could set the side widget on the left, but I did not manage to do it with the current version.

**Comment by tsquez** [comment]
Hey there,

Yes it does look bad which is why I cannot wait for 6.5 to come out. I will be removing all the css options and just going with the XY Grid. That is the one that is more stable.

In the mean time if you like use this css to make the menu look better:

`
#secondary .menu a {padding:0;}
#secondary li {width:100%;padding:10px 0 5px;}
#secondary li li {width:100%;}
#secondary ul li li {margin-left:16px;}`

Hope this helps. Please let me know if you need assistance with anything else.
